# Project: Dibuixos
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o dibuixos.o demo.o
LINKOBJ  = main.o dibuixos.o demo.o
LIBS     = -L"C:/Programas/Dev-Cpp/MinGW64/lib" -L"C:/Programas/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -L"C:/Programas/Dev-Cpp/MinGW64/freeglut/lib/x64" -static-libgcc -lglu32 -lfreeglut_static -lopengl32 -lwinmm -lgdi32 -Wl,--subsystem,windows -g3
INCS     = -I"C:/Programas/Dev-Cpp/MinGW64/include" -I"C:/Programas/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Programas/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Programas/Dev-Cpp/MinGW64/freeglut/include"
CXXINCS  = -I"C:/Programas/Dev-Cpp/MinGW64/include" -I"C:/Programas/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Programas/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Programas/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"C:/Programas/Dev-Cpp/MinGW64/freeglut/include"
BIN      = Dibuixos.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3 -D FREEGLUT_STATIC -include pch.h
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

dibuixos.o: dibuixos.c
	$(CC) -c dibuixos.c -o dibuixos.o $(CFLAGS)

demo.o: demo.c
	$(CC) -c demo.c -o demo.o $(CFLAGS)
