.PHONY: clean All

All:
	@echo "----------Building project:[ dibuixos - Debug ]----------"
	@"$(MAKE)" -f  "dibuixos.mk" pch.h.gch && "$(MAKE)" -f  "dibuixos.mk" && "$(MAKE)" -f  "dibuixos.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ dibuixos - Debug ]----------"
	@"$(MAKE)" -f  "dibuixos.mk" clean
